### ISSUE TITLE
Not compiling anymore

### ISSUE THREAD

**Issue by DinoSane** [gizur/odataserver2#4]
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.18.6-200.fc21.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/dominios/odata/node_modules/leveldbstreams/node_modules/leveldown
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by DinoSane** [comment]
I made it. Just update nodejs
